/**
 * @fileoverview gRPC-Web generated client stub for orderService
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: orderService.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.orderService = require('./orderService_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.orderService.OrderServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.orderService.OrderServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.orderService.OrderRequest,
 *   !proto.orderService.OrderResponse>}
 */
const methodDescriptor_OrderService_PlaceOrder = new grpc.web.MethodDescriptor(
  '/orderService.OrderService/PlaceOrder',
  grpc.web.MethodType.UNARY,
  proto.orderService.OrderRequest,
  proto.orderService.OrderResponse,
  /**
   * @param {!proto.orderService.OrderRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.orderService.OrderResponse.deserializeBinary
);


/**
 * @param {!proto.orderService.OrderRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.orderService.OrderResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.orderService.OrderResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.orderService.OrderServiceClient.prototype.placeOrder =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/orderService.OrderService/PlaceOrder',
      request,
      metadata || {},
      methodDescriptor_OrderService_PlaceOrder,
      callback);
};


/**
 * @param {!proto.orderService.OrderRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.orderService.OrderResponse>}
 *     Promise that resolves to the response
 */
proto.orderService.OrderServicePromiseClient.prototype.placeOrder =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/orderService.OrderService/PlaceOrder',
      request,
      metadata || {},
      methodDescriptor_OrderService_PlaceOrder);
};


module.exports = proto.orderService;

