/**
 * @fileoverview gRPC-Web generated client stub for price
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: price.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.price = require('./price_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.price.PricingClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.price.PricingPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.price.PriceRequest,
 *   !proto.price.PriceResponse>}
 */
const methodDescriptor_Pricing_CalculatePricing = new grpc.web.MethodDescriptor(
  '/price.Pricing/CalculatePricing',
  grpc.web.MethodType.UNARY,
  proto.price.PriceRequest,
  proto.price.PriceResponse,
  /**
   * @param {!proto.price.PriceRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.price.PriceResponse.deserializeBinary
);


/**
 * @param {!proto.price.PriceRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.price.PriceResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.price.PriceResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.price.PricingClient.prototype.calculatePricing =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/price.Pricing/CalculatePricing',
      request,
      metadata || {},
      methodDescriptor_Pricing_CalculatePricing,
      callback);
};


/**
 * @param {!proto.price.PriceRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.price.PriceResponse>}
 *     Promise that resolves to the response
 */
proto.price.PricingPromiseClient.prototype.calculatePricing =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/price.Pricing/CalculatePricing',
      request,
      metadata || {},
      methodDescriptor_Pricing_CalculatePricing);
};


module.exports = proto.price;

