/**
 * @fileoverview gRPC-Web generated client stub for productsService
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: products.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.productsService = require('./products_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.productsService.GetProductsServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.productsService.GetProductsServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.productsService.ProductsRequest,
 *   !proto.productsService.ProductsResponse>}
 */
const methodDescriptor_GetProductsService_GetProducts = new grpc.web.MethodDescriptor(
  '/productsService.GetProductsService/GetProducts',
  grpc.web.MethodType.UNARY,
  proto.productsService.ProductsRequest,
  proto.productsService.ProductsResponse,
  /**
   * @param {!proto.productsService.ProductsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.productsService.ProductsResponse.deserializeBinary
);


/**
 * @param {!proto.productsService.ProductsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.productsService.ProductsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.productsService.ProductsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.productsService.GetProductsServiceClient.prototype.getProducts =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/productsService.GetProductsService/GetProducts',
      request,
      metadata || {},
      methodDescriptor_GetProductsService_GetProducts,
      callback);
};


/**
 * @param {!proto.productsService.ProductsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.productsService.ProductsResponse>}
 *     Promise that resolves to the response
 */
proto.productsService.GetProductsServicePromiseClient.prototype.getProducts =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/productsService.GetProductsService/GetProducts',
      request,
      metadata || {},
      methodDescriptor_GetProductsService_GetProducts);
};


module.exports = proto.productsService;

